repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: bash -c 'flake8 lookout && isort -c --diff lookout && black -c lookout'
        language: system
        types: [python]
