repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: bash -c 'flake8 setup.cfg && isort -c --diff pyproject.toml && black --check pyproject.toml'
        language: system
        types: [python]