repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: bash -c 'flake8 --extend-ignore E203 --max-line-length 119 && isort -c --diff pyproject.toml && black --check pyproject.toml'
        language: system
        types: [python]
